const f = () => {
    try {
        let a = 0
        // console.log(program)
        console.log("Program ran successfully")
        return
    }
    catch (err) {
        console.log("This is an error")
        console.log(p)
    }
    finally {
        console.log("i am good boy")
    }
}
f()
console.log("End")